### ISSUE TITLE
"Infrastsructure as Code?"?

### ISSUE THREAD

**Issue by BenLubar** [tdwtf/WtfAds#1]
These ads have Infrastructure spelled incorrectly on the right:

https://github.com/tdwtf/WtfAds/blob/master/728x90/Inedo1/inedo-728by90_intro-otter5.png
https://github.com/tdwtf/WtfAds/blob/master/728x90/Inedo2/inedo-728by90_intro-otter5.png
https://github.com/tdwtf/WtfAds/blob/master/728x90/Inedo3/inedo-728by90_intro-otter5.png
https://github.com/tdwtf/WtfAds/blob/master/728x90/Inedo4/inedo-728by90_intro-otter5.png

**Comment by patrickwroach** [comment]
Uploaded the new images.  
Should be good when we next push to production, are we good to do that immediately?
